### ISSUE TITLE
[Bug] Unable to install 1.6 certification tool

### ISSUE THREAD

**Issue by drempelg** [project-chip/certification-tool#834]
### Describe the bug

checked out the tag for 1.5 listed in this document:

https://groups.csa-iot.org/wg/members-all/document/41923

Followed the instructions and got this, multiple times.

********************************************************************************
1.2-install-additional-dependencies.sh: Installing additional package: libgstreamer1.0-dev (>=1.16.0)
********************************************************************************
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmount-dev : Depends: libblkid-dev but it is not going to be installed
                Depends: libmount1 (= 2.39.3-9ubuntu6) but 2.39.3-9ubuntu6.3 is to be installed
 libzstd-dev : Depends: libzstd1 (= 1.5.5+dfsg2-2build1) but 1.5.5+dfsg2-2build1.1 is to be installed
E: Unable to correct problems, you have held broken packages.

################################################################################
################################################################################

Please try the installation again and if the problem persists,
please collect as much information as possible and file an issue here:
https://github.com/project-chip/certification-tool/issues

**Comment by drempelg** [comment]
This was on a Pi4 using ubuntu.

**Comment by rquidute** [comment]
Hi @drempelg could you please share the installation logs? 
They can be found at `~/certification-tool/logs` folder. 
In addition, please share the output for `./scripts/th/th-doctor.sh --complete`.

**Comment by drempelg** [comment]
_____         _     _   _                                  ____             _
      |_   _|__  ___| |_  | | | | __ _ _ __ _ __   ___  ___ ___  |  _ \  ___   ___| |_ ___  _ __
        | |/ _ \/ __| __| | |_| |/ _` | '__| '_ \ / _ \/ __/ __| | | | |/ _ \ / __| __/ _ \| '__|
        | |  __/\__ \ |_  |  _  | (_| | |  | | | |  __/\__ \__ \ | |_| | (_) | (__| || (_) | |
        |_|\___||___/\__| |_| |_|\__,_|_|  |_| |_|\___||___/___/ |____/ \___/ \___|\__\___/|_|

                                      Mon Dec 29 11:30:59 PST 2025

permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/json": dial unix /var/run/docker.sock: connect: permission denied
+---------------------------------------- Test Harness Version ----------------------------------------+
|                                                                                                      |
|  Test Engine Version: The 'certification-tool-backend-1' container it not running.                   |
|  Test Engine SHA: The 'certification-tool-backend-1' container it not running.                       |
|  Test Engine SDK SHA: The 'certification-tool-backend-1' container it not running.                   |
|                                                                                                      |
|  certification-tool-backend-1                                                                        |
|       The container is not running.                                                                  |
|                                                                                                      |
|  certification-tool-frontend-1                                                                       |
|       The container is not running.                                                                  |
|                                                                                                      |
|  certification-tool-db-1                                                                             |
|       The container is not running.                                                                  |
|                                                                                                      |
|  certification-tool-proxy-1                                                                          |
|       The container is not running.                                                                  |
|                                                                                                      |
+------------------------------------------------------------------------------------------------------+

+----------------------------------------- Repository Details -----------------------------------------+
|                                                                                                      |
|  +-----------------------------------------------------------------------------------------------+   |
|  |  Test Harness: certification-tool                                                             |   |
|  +-----------------------------------------------------------------------------------------------+   |
|  Commit SHA: d0d8f486b701467e16d3d59b914a6fde80646c7a                                                |
|  Commit Message: [FIX] Updating user guide for Matter 1.5 finale version (#798)* Updating user ...   |
|  Commit Author: antonio-amjr                                                                         |
|  Commit Date: 2025-11-18 11:32:21 -0300                                                              |
|  Contained in branches:                                                                              |
|      * v2.14+fall2025                                                                                |
|      Tracking: origin/v2.14+fall2025                                                                 |
|                                                                                                      |
|  +-----------------------------------------------------------------------------------------------+   |
|  |  Frontend: certification-tool                                                                 |   |
|  +-----------------------------------------------------------------------------------------------+   |
|  Commit SHA: d0d8f486b701467e16d3d59b914a6fde80646c7a                                                |
|  Commit Message: [FIX] Updating user guide for Matter 1.5 finale version (#798)* Updating user ...   |
|  Commit Author: antonio-amjr                                                                         |
|  Commit Date: 2025-11-18 11:32:21 -0300                                                              |
|  Contained in branches:                                                                              |
|      * v2.14+fall2025                                                                                |
|      Tracking: origin/v2.14+fall2025                                                                 |
|                                                                                                      |
|  +-----------------------------------------------------------------------------------------------+   |
|  |  Backend: certification-tool                                                                  |   |
|  +-----------------------------------------------------------------------------------------------+   |
|  Commit SHA: d0d8f486b701467e16d3d59b914a6fde80646c7a                                                |
|  Commit Message: [FIX] Updating user guide for Matter 1.5 finale version (#798)* Updating user ...   |
|  Commit Author: antonio-amjr                                                                         |
|  Commit Date: 2025-11-18 11:32:21 -0300                                                              |
|  Contained in branches:                                                                              |
|      * v2.14+fall2025                                                                                |
|      Tracking: origin/v2.14+fall2025                                                                 |
|                                                                                                      |
|  +-----------------------------------------------------------------------------------------------+   |
|  |  Cli: certification-tool                                                                      |   |
|  +-----------------------------------------------------------------------------------------------+   |
|  Commit SHA: d0d8f486b701467e16d3d59b914a6fde80646c7a                                                |
|  Commit Message: [FIX] Updating user guide for Matter 1.5 finale version (#798)* Updating user ...   |
|  Commit Author: antonio-amjr                                                                         |
|  Commit Date: 2025-11-18 11:32:21 -0300                                                              |
|  Contained in branches:                                                                              |
|      * v2.14+fall2025                                                                                |
|      Tracking: origin/v2.14+fall2025                                                                 |
|                                                                                                      |
+------------------------------------------------------------------------------------------------------+

Displays Test Harness setup information.

Usage:

    Show TH version and repository details:    ./scripts/th/th-doctor.sh
    Show TH host OS system information:        ./scripts/th/th-doctor.sh --system
    Show TH host OS network information:       ./scripts/th/th-doctor.sh --network
    Show TH host OS environment details:       ./scripts/th/th-doctor.sh --environment
    Show TH DUT configuration details:         ./scripts/th/th-doctor.sh --more
    Show TH Docker Container Logs:             ./scripts/th/th-doctor.sh --docker-logs
    Show all TH details:                       ./scripts/th/th-doctor.sh --complete

ubuntu@ubuntu:~/certification-tool$

**Comment by drempelg** [comment]
[logs.zip](https://github.com/user-attachments/files/24372916/logs.zip)

**Comment by drempelg** [comment]
done

**Comment by rquidute** [comment]
Hi @drempelg  We've identified the root cause of the installation failure you experienced. The issue is a temporary version mismatch between system libraries and their development packages in the Ubuntu repositories.

#  Please try this fix first:

```
  # Run these commands to fix the dependency mismatch
  sudo apt-get update
  sudo apt-get install --only-upgrade -y libmount-dev libzstd-dev libblkid-dev
```

```
  # Now re-run the installation
  cd ~/certification-tool
  ./scripts/ubuntu/auto-install.sh
```

  This should resolve the libgstreamer1.0-dev installation error.



#   If the above doesn't work:

  As a last resort, try a fresh installation with a formatted SD card:

  1. Format your SD card and install a fresh Ubuntu 24.04 image
  2. Clone the repository:
  git clone -b v2.14+fall2025 https://github.com/project-chip/certification-tool.git --recurse-submodules
  cd certification-tool
  3. Run the installation:
  ./scripts/ubuntu/auto-install.sh

  Why this should work now:

The Ubuntu package repositories have recently been updated with newer development package versions that match the security-updated system libraries. A fresh installation will pull these updated packages, avoiding the version mismatch that caused your original failure.

Let me know if you encounter any issues.

**Comment by rquidute** [comment]
Closing this issue. Please check the explanation in the previous comment. Fell free the create a new GitHub issue, in case the error persists.

**Comment by drempelg** [comment]
This problem still persists, I get the same error with a fresh install of 24.04.3 LTS, and doing the same steps.

**Comment by drempelg** [comment]
wished you hadn't closed this...

**Comment by drempelg** [comment]
I don't think the fix made it into the 2.14-fall2025 branch.  It says I'm up to date, but the commit is from Nov 18

**Comment by drempelg** [comment]
I just cloned master to see if it works, I think it's doing better. Takes a long time so not sure yet.

**Comment by drempelg** [comment]
master installs fine, just not the branch

**Comment by rquidute** [comment]
Hi @drempelg I'm reopening this issue. Please always attach the logs, commands you are using, everything that would help us to investigate the problem.

**Comment by rquidute** [comment]
The 2.14-fall2025 branch remains unchanged. Updates were applied to the individual library repositories instead.

**Comment by rquidute** [comment]
Please try it again with a formatted sd card using the commands bellow and shared your findings:
```
git clone -b v2.14+fall2025 https://github.com/project-chip/certification-tool.git --recurse-submodules
cd certification-tool
./scripts/ubuntu/auto-install.sh
```

**Comment by ribsey** [comment]
I ran into the same issue, but with the branch `v2.12+spring2025` and different dependencies.

Luckily I found the fix online.
There are not all apt repositories activated by default in the RaspberryPi ubuntu server 24.04.3 image.

To get all updates available, edit `/etc/apt/sources.list.d/ubuntu.sources` and change:
```
Suites: noble
```
To:
```
Suites: noble noble-updates
```

This did the trick for me.

**Comment by rquidute** [comment]
Closed as completed
